FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY Api/ ./Api/
COPY Shared/ ./Shared/

RUN dotnet restore "Api/Api.csproj" --force
RUN dotnet publish "Api/Api.csproj" -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app .
EXPOSE 7276
ENV ASPNETCORE_URLS=http://+:$PORT
CMD ["dotnet", "Api.dll"]
